_target_: src.models.gauss_module.gaussLitModule
lr: 0.001
weight_decay: 0.0005
data_dir: ${data_dir}
name: ${name}


net:
  _target_: src.models.components.gauss_net.SimpleDenseNet_LR2_gauss
  input_size: 100
  lin1_size: 64
  lin2_size: 32
  lin3_size: 16
  output_size: 2
