_target_: src.datamodules.gauss_datamodule.gaussDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
train_val_test_split: [40_000, 5_000, 5_000]
num_workers: 0
pin_memory: False
